### ISSUE TITLE
Is there any example of training code with mnist data?

### ISSUE THREAD

**Issue by jiahui-zhao** [microsoft/CryptoNets#10]
Sorry for this simple question. I resently know about neural networks and then find your great project. Unfortunately, i'm a newcomer to this area and i have a duty to create my own cryptonet with my datasets which are 128*128 grayscale images. So i think maybe an example of training code with mnist data can be helpful. If you have the code, could you please share to me? Thank you very much!

**Comment by ranigb** [comment]
You can use any training pipeline out there. There are only a couple of things to keep in mind:
1. keep the network shallow
2. use square activation functions

as an alternative you can use the transfer learning technique to as demonstrated on the Caltech-101 dataset (check the LoLa paper)

**Comment by jiahui-zhao** [comment]
Thank you for your patience! I already know the key of this project, I'm trying to finish it with my own dataset. Thank you for your great contirbutions!
