### ISSUE TITLE
Issue with building 

### ISSUE THREAD

**Issue by jchen98** [microsoft/CryptoNets#11]
Hello, I am using SEAL 3.2.2 and running into some issues. This is what I encountered when trying to compile Cryptonets for the first time.  I have installed all the packages that were originally missing but I'm not sure whether the repo is missing some dll files. Any help would be appreciated! 

![seal](https://user-images.githubusercontent.com/6350132/75511982-f9a12500-59bd-11ea-8f9a-4629d06ef9c6.JPG)

**Comment by ranigb** [comment]
It looks like you are missing SEALNET. Try to make sure you have it compiled correctly and that you are pointing to it in the CryptoNets code.
