### ISSUE TITLE
the scaled mean pool layer of cryptonets 

### ISSUE THREAD

**Issue by palettis** [microsoft/CryptoNets#17]
From the description of the cryptonets, we find the input of layer 3 is 5 * 13 * 13，and the output of the layer 3 is also 5 * 13 * 13.  But the windows is 1 * 3 * 3, and ther is no padding and stride declaration. why the output of layer 3 is  5 * 13 * 13? why the output of pool layer won`t be smaller?
![image](https://user-images.githubusercontent.com/52186110/88616165-fffb1080-d0c5-11ea-9f84-5c2a8cedfbd6.png)

**Comment by pinglanliu** [comment]
Have you figured this out? I have the same confusion.
